### ISSUE TITLE
Criar Branches 9.5 e 9.5 - dev

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/pdf#1]
Criar branch 9.5 e 9.5 - dev exibindo no vscode e repositório do github

**Comment by verdanatech-luana** [comment]
Branches criadas.

![2021-08-16_14-06](https://user-images.githubusercontent.com/86842154/129602450-30a1953b-145e-47e2-9dcd-80ef72abdb03.png)

![2021-08-16_14-08](https://user-images.githubusercontent.com/86842154/129602484-c7cb3a2f-f483-43c7-a46b-53d14361ca08.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente no GLPI - 9.5.
![TestePDF](https://user-images.githubusercontent.com/80538863/129728414-c057460b-d78a-43ee-84a6-3283e9f1353b.png)
